### PR TITLE
Add support for Brizy detection

### PR DESCRIPTION
**Pull request by jdevalk**
This adds support for the detection of both Brizy Cloud (a CMS / Page Builder) and Brizy WordPress (a Page Builder / WordPress plugin).

First two test sites use Brizy Cloud, the latter two use Brizy WordPress.

---

**Test websites**:

- https://www.brizy.io/
- https://www.growinromania.com/
- https://sdsriskassist.ca/
- https://thepenthomes.millatbroadway.com/

### CODE REVIEW

**Comment by tunetheweb** [comment]
@pmeenan could we remove the `detected_raw` segment from this output? Seems to just repeat the previous segments so would make it half the size.

**Review by tunetheweb — APPROVED** [review]
LGTM

**Comment by pmeenan** [comment]
> @pmeenan could we remove the `detected_raw` segment from this output? Seems to just repeat the previous segments so would make it half the size.

[Done](https://github.com/HTTPArchive/wptagent/commit/89b8f421bae8c7e56c0bf8b934aff2d31be9276a)

**Comment by tunetheweb** [comment]
Thank you!!

**Pull request merged**
