### PR TITLE
Quality control improvements

### PR DESCRIPTION
**Pull request by max-ostapenko**
Improving the maintenance effort as discussed in the [doc](https://docs.google.com/document/d/1jGhvtpaatOJTh5LGcd42hyrt8lNRmK_f4PaCHf3kR_M/edit).
Related to the issue #21.

The outline:
- [x] PR action picks up the updated technologies definitions and author-defined test URLs
- [x] It send technologies update to a WPT instance (assisted by @pmeenan)
- [x] Runs unit tests
- [x] Start a test for a list of URLs
- [x] Comments with the detected technologies in the PR

WPT nodeJS client PRs required for this workflow:
1. [Sync updates from upstream #3](https://github.com/HTTPArchive/WebPageTest.api-nodejs/pull/3)
2. [Pull the Wappalyzer config for a single test #4](https://github.com/HTTPArchive/WebPageTest.api-nodejs/pull/4)

### CODE REVIEW

**Comment by max-ostapenko** [comment]
@rviscomi could we drop the requirement of providing technology icons?
It would simplify the contributions and maintenance effort.

**Comment by max-ostapenko** [comment]
@rviscomi Once you add the WPT key we should be able to see result of unit tests and technologies for the test websites run with the live version of rules.
With PROD technology rules while there is no WPT API yet.

And it seems that [live tests](https://webpagetest.httparchive.org/result/240503_KY_4/) are broken now: 
`"wappalyzer_failed": 1,`

**Comment by rviscomi** [comment]
>@rviscomi could we drop the requirement of providing technology icons?
>It would simplify the contributions and maintenance effort.

We may want to display the icons in the CWV Tech Report ([mockup](https://github.com/HTTPArchive/cwv-tech-report/discussions/30)) so let's try to keep it as a requirement if possible

**Comment by max-ostapenko** [comment]
@rviscomi this PR is only waiting for a WPT API key saved in secrets to be ready for review.

**Comment by pmeenan** [comment]
@max-ostapenko `HA_API_KEY` is now set for this repository with an API key for the webpagetest.httparchive.org instance.

**Comment by max-ostapenko** [comment]
@pmeenan please review & merge.
Fork's PRs don't have access to secrets until merged.

**Pull request merged**
